config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about' => 'pages#about'

  resources :questions, only: [:index, :show]
end

app/models/question.rb
class Question < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, use: [:slugged, :finders]
  acts_as_taggable

  def next
    self.class.where('id > ?', id).first
  end

  def previous
    self.class.where('id < ?', id).last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    load_questions
  end

  def show
    load_question
  end

  protected

  def load_questions
    @questions = Question.all
  end

  def load_question
    @question = Question.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header_link_to(label, url)
    klass = current_page?(url) ? 'active' : ''
    content_tag :li, class: klass do
      link_to(label, url)
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def markdown(text)
    render_options = {
        filter_html: true,
        hard_wrap: true,
        link_attributes: {rel: 'nofollow'}
    }
    renderer = HTML.new(render_options)

    extensions = {
        autolink: true,
        fenced_code_blocks: true,
        lax_spacing: true,
        no_intra_emphasis: true,
        strikethrough: true,
        superscript: true
    }
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Kalkomey</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'shared/header' %>

  <div class="container">
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/about.html.erb
<h1><%= fa_icon 'user' %> About</h1>

<br>
<strong>Emiliano Qaqi</strong></br>
<strong>Phone: (407)913-4526</strong></br>
<br>

<p>A beyond senior level developer with startup architecture capabilities and a serial entrepreneur in the crossroad of Augmentation, experimentation on mobile and web technologies.</p>

<p>Exploring designs, economies that tap into the global commons, which will distribute capacity, embrace paradox and reshape the future.</p>

<p>This phrase is always in my mind and makes me develop applications that actually work for my customers' perspective in order to achieve success. Performing for great organizations and finding great innovations is simply great in my résumé, although initiates the difference in establishing projects that intriguer people's interest.</p>

<p>When it comes to creating the next idea or the next invention; my current clients look no further, but to contact me. I do not just provide special, complex, intuitive services, but I also specialize in the latest aspects of marketing, advertising, funding, trademarking, patenting, copyrighting, and generally entrepreneurial innovations. </p>

<p>These aspects of life shaped my design culture and persuaded me to realize that the highest success in design is to achieve ambiguity. On the other hand, programming is an approach from a different angle; that of perfectionism and functional physics in motion.</p>

<strong>Available for consulting services in the following technologies:</strong>
<ul>
<li>Mobile Development (iOS and Android)</li>
<li>Custom Software Development</li>
<li>Full Stack Web Development</li>
<li>Startup Development</li>
<li>Business Consulting</li>
<li>eCommerce Development</li>
<li>Experimental programing in vision technologies (such as image recognition), big data, machine learning and neural networks with quant/predictive potentials.</li>
<li>Startup Development and Business Consulting</li>
<li>Salesforce and SAP</li>
</ul>

app/views/pages/home.html.erb
<div class='description'>
  <h1>Kalkomey Questions</h1>
  <p class='lead'>The purpose of this app is to show my knowledge of Ruby on Rails and supporting technologies.</p>
</div>

<hr>

<div class='row'>
  <div class='col-xs-12 col-sm-6 col-sm-offset-3'>
    <div class='row'>
      <div class='col-xs-12 col-sm-6 text-center'>
        <%= link_to :questions, class: 'btn btn-primary btn-lg home-button' do %>
          <%= fa_icon 'th-list' %>
          Questions
        <% end %>
      </div>

      <div class='col-xs-12 col-sm-6 text-center'>
        <%= link_to :about, class: 'btn btn-primary btn-lg home-button' do %>
          <%= fa_icon 'user' %>
          About
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<h1><%= fa_icon 'th-list' %> Questions</h1>

<% @questions.each_with_index do |question, i| %>
  <%= link_to question, class: 'btn btn-default btn-block question' do %>
    <span class='badge'><%= i+1 %></span>
    <%= question.title %>
  <% end %>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<% @question.tags.each do |tag| %>
  <span class='label label-primary'><%= tag.name %></span>
<% end %>
<br>

<% if @question.additional_info.present? %>
  <br>
  <strong>Additional Info:</strong>
  <pre><%= @question.additional_info %></pre>
<% end %>

<br>
<strong>Answer:</strong>
<% if @question.answer %>
  <p><%= raw markdown(@question.answer) %></p>
<% end %>


<div class='row'>
  <div class='col-xs-12 col-sm-4 text-center'>
    <%= link_to "#{fa_icon('chevron-left')} Previous".html_safe, question_path(@question.previous), class: 'btn btn-primary' if @question.previous.present? %>
  </div>
  <div class='col-xs-12 col-sm-4 text-center'>
    <%= link_to "#{fa_icon('th-list')} Back to Questions".html_safe, :questions, class: 'btn btn-default' %>
  </div>
  <div class='col-xs-12 col-sm-4 text-center'>
    <%= link_to "#{fa_icon('chevron-right')} Next".html_safe, question_path(@question.next), class: 'btn btn-primary'  if @question.next.present? %>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'Kalkomey', :root, class: 'navbar-brand' %>
    </div>

    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= header_link_to 'Home', :root %>
        <%= header_link_to 'About', :about %>
        <%= header_link_to 'Questions', :questions %>
      </ul>
    </div>
  </div>
</nav>